---
exclude: custom_components
exclude: www/community

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
#      - id: trailing-whitespace
#      - id: end-of-file-fixer
#       exclude: .HA_VERSION
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: sort-simple-yaml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
  - repo: https://github.com/psf/black.git
    rev: 19.3b0
    hooks:
      - id: black
