- id: '1573571236003'
  alias: Daily Backups
  description: Do daily backups to Google Drive
  trigger:
  - at: '4:00'
    platform: time
  condition: []
  action:
  - service: rest_command.google_backup
- id: '1573571285285'
  alias: Daily Snapshot
  description: Create a snapshot daily
  trigger:
  - at: '3:00'
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full
- alias: rfbridge_demultiplexer
  trigger:
  - platform: mqtt
    topic: rfbridge/tele/RESULT
  action:
  - service: python_script.rfbridge_demux
    data_template:
      payload: '{{trigger.payload_json.RfReceived.Data}}'
  id: ac2012f9731d497e8c073d4d90c79fe3
- id: '1574804485540'
  alias: Xmas Tree On
  description: ''
  trigger:
  - entity_id: binary_sensor.xmas_tree_remote_on
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.xmas_tree
    service: switch.turn_on
- id: '1574805062180'
  alias: Xmas Tree Off
  description: ''
  trigger:
  - entity_id: binary_sensor.xmas_tree_remote_off
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.xmas_tree
    service: switch.turn_off
- id: '1575669296134'
  alias: Turn on kitchen led at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: 4b9664338d2d4d88b65ca5e673f96ed7
    domain: light
    entity_id: light.kitchen_led
    type: turn_on
- id: '1575669351282'
  alias: Turn off kitchen led at night
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - device_id: 4b9664338d2d4d88b65ca5e673f96ed7
    domain: light
    entity_id: light.kitchen_led
    type: turn_off
- id: '1576080686658'
  alias: turn on retro lamp at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: e642a488b5704c30869ad499eaf607af
    domain: switch
    entity_id: switch.retro_lamp
    type: turn_on
- id: '1576080735886'
  alias: turn off retro lamp at night
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - device_id: e642a488b5704c30869ad499eaf607af
    domain: switch
    entity_id: switch.retro_lamp
    type: turn_off
- id: '1578327288889'
  alias: Office Lights
  description: Turn on lights when door opens. Ignore door close since I keep it closed
    anyway.
  trigger:
  - entity_id: binary_sensor.office_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.office_sonoff_mini
    service: switch.turn_on
- id: '1578795783188'
  alias: My Closet On when door open daytime
  description: ''
  trigger:
  - entity_id: binary_sensor.my_closet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '8:00'
    before: '20:30'
    condition: time
  action:
  - data:
      brightness_pct: 100
    entity_id: light.my_closet_bulb
    service: light.turn_on
- id: '1578795816492'
  alias: My Closet off when door closed
  description: ''
  trigger:
  - entity_id: binary_sensor.my_closet
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.my_closet_bulb
    service: light.turn_off
- id: '1578796877324'
  alias: Crystal Closet On With Door Open - Daytime
  description: ''
  trigger:
  - entity_id: binary_sensor.crystal_closet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '9:00'
    before: '20:30'
    condition: time
  action:
  - data:
      brightness_pct: 75
    entity_id: light.c_closet_bulb
    service: light.turn_on
- id: '1578796925401'
  alias: Crystal Closet Off with Door Shut
  description: ''
  trigger:
  - entity_id: binary_sensor.crystal_closet
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.c_closet_bulb
    service: light.turn_off
- id: '1578925720315'
  alias: My Closet On With Door Open Nighttime
  description: ''
  trigger:
  - entity_id: binary_sensor.my_closet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '20:30'
    before: '8:00'
    condition: time
  action:
  - data:
      brightness_pct: 33
    entity_id: light.my_closet_bulb
    service: light.turn_on
- id: '1578934076812'
  alias: Living Room Lights
  description: Specifically the lights behind the couch
  trigger:
  - entity_id: binary_sensor.living_room_remote
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.behind_couch
    service: switch.toggle
- id: '1579010849983'
  alias: Crystal Closet On With Door Open - Nighttime
  description: ''
  trigger:
  - entity_id: binary_sensor.crystal_closet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '20:30'
    before: '9:00'
    condition: time
  action:
  - data:
      brightness_pct: 33
    entity_id: light.c_closet_bulb
    service: light.turn_on
- id: '1579028749851'
  alias: flash my office lights when motion is detected
  description: ''
  trigger:
  - device_id: 6489cd6648a944cd8be6fc4046354763
    domain: binary_sensor
    entity_id: binary_sensor.basement_motion_motion
    platform: device
    type: motion
  condition:
  - condition: state
    entity_id: light.office_lights
    state: 'on'
  action:
  - entity_id: light.office_lights
    service: light.turn_off
  - delay: '1'
  - entity_id: light.office_lights
    service: light.turn_on
