---

- id: '1573571236003'
  alias: Daily Backups
  description: Do daily backups to Google Drive
  trigger:
  - at: '4:00'
    platform: time
  condition: []
  action:
  - service: rest_command.google_backup

- id: '1573571285285'
  alias: Daily Snapshot
  description: Create a snapshot daily
  trigger:
  - at: '3:00'
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full

- id: ac2012f9731d497e8c073d4d90c79fe3
  alias: rfbridge_demultiplexer
  trigger:
  - platform: mqtt
    topic: rfbridge/tele/RESULT
  action:
  - service: python_script.rfbridge_demux
    data_template:
      payload: '{{trigger.payload_json.RfReceived.Data}}'

- id: '1575669296134'
  alias: Turn on kitchen led at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.kitchen_led

- id: '1575669351282'
  alias: Turn off kitchen led at night
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.kitchen_led

- id: '1576080686658'
  alias: turn on retro lamp at sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.retro_lamp

- id: '1576080735886'
  alias: turn off retro lamp at night
  description: ''
  trigger:
  - at: '23:30'
    platform: time
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.retro_lamp

- id: '1578327288889'
  alias: Office Lights
  description: Turn on lights when door opens. Ignore door close since I keep it closed
    anyway.
  trigger:
  - entity_id: binary_sensor.office_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.office_sonoff_mini
  - service: switch.turn_on
    entity_id: switch.circadian_lighting_office
  - service: light.turn_on
    entity_id: light.office_lights

- id: '1578223342231'
  alias: Office Light Switch
  description: Make the office light switch do what one would expect from a proper switch
  trigger:
  - entity_id: binary_sensor.office_sonoff_mini_switch1
    platform: state
  condition: []
  action:
  - service: light.toggle
    entity_id: light.office_lights

- id: '1578795783188'
  alias: My Closet On when door open daytime
  description: ''
  trigger:
  - entity_id: binary_sensor.my_closet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '8:00'
    before: '20:30'
    condition: time
  action:
  - service: light.turn_on
    entity_id: light.my_closet_bulb
    data:
      brightness_pct: 100

- id: '1578795816492'
  alias: My Closet off when door closed
  description: ''
  trigger:
  - entity_id: binary_sensor.my_closet
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.my_closet_bulb

- id: '1578796877324'
  alias: Crystal Closet On With Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.crystal_closet
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.c_closet_bulb
    data:
      brightness_pct: 75

- id: '1578796925401'
  alias: Crystal Closet Off with Door Shut
  description: ''
  trigger:
  - entity_id: binary_sensor.crystal_closet
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.c_closet_bulb

- id: '1578925720315'
  alias: My Closet On With Door Open Nighttime
  description: ''
  trigger:
  - entity_id: binary_sensor.my_closet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '20:30'
    before: '8:00'
    condition: time
  action:
  - service: light.turn_on
    entity_id: light.my_closet_bulb
    data:
      brightness_pct: 33

- id: '1578934076812'
  alias: Living Room Lights
  description: Lights behind the couch toggle with one button remote
  trigger:
  - entity_id: binary_sensor.living_room_remote
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: switch.toggle
    entity_id: group.ikea

- id: '1579028749851'
  alias: flash my office lights when motion is detected
  description: ''
  trigger:
  - device_id: 6489cd6648a944cd8be6fc4046354763
    domain: binary_sensor
    entity_id: binary_sensor.basement_motion_motion
    platform: device
    type: motion
  condition:
  - condition: state
    entity_id: light.office_lights
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.office_lights
  - delay: '1'
  - service: light.turn_on
    entity_id: light.office_lights

- id: '1578796877387'
  alias: Laundry Room On With Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.laundry_room
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.laundry_lights
    data:
      brightness_pct: 80

- id: '1578796925422'
  alias: Laundry Room Off with Door Shut
  description: ''
  trigger:
  - entity_id: binary_sensor.laundry_room
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.laundry_lights

- id: '7573212710929'
  alias: Storage Room On With Door Open
  description: ''
  trigger:
  - entity_id: binary_sensor.storage_room
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.storage_sonoff_mini

- id: '3724804963566'
  alias: Storage Room Off with Door Shut
  description: ''
  trigger:
  - entity_id: binary_sensor.storage_room
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.storage_sonoff_mini
