---
default_config:

homeassistant:
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:
  themes: !include themes.yaml

ring:
  username: !secret ring_email
  password: !secret ring_password

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarmdotcom_username
  password: !secret alarmdotcom_password

sensor:
  platform: ring

binary_sensor:
  - platform: ring

camera:
  - platform: ring

plant:
  office:
    sensors:
      moisture: sensor.plant_soil_moisture
    min_moisture: 50
    max_moisture: 80

scene:
  platform: hunterdouglas_powerview
  address: 10.0.0.7

sleepiq:
  username: !secret sleepiq_username
  password: !secret sleepiq_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

recorder:
  db_url: !secret mysql_url

rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

panel_iframe:
  zwave2mqtt:
    title: Z-Wave to MQTT
    icon: mdi:z-wave
    url: http://10.0.0.190:8091

mqtt:
  discovery: true
  discovery_prefix: 'ha'
  broker: mosquitto_core
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'