---
cloud:

config:

history:
  include:
    domains:
      - sensor
      - switch
      - person
      - binary_sensor

logbook:
  exclude:
    domains:
      - sun

mobile_app:

person:

ssdp:

sun:

system_health:

zeroconf:

homeassistant:
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes

binary_sensor:

  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error

  - platform: mqtt
    name: 'Xmas_tree_remote_on'
    state_topic: 'home/remote_1_button_1'
    off_delay: 1

  - platform: mqtt
    name: 'Xmas_tree_remote_off'
    state_topic: 'home/remote_1_button_2'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b1'
    state_topic: 'home/office_remote_b1'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b2'
    state_topic: 'home/office_remote_b2'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b3'
    state_topic: 'home/office_remote_b3'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b4'
    state_topic: 'home/office_remote_b4'
    off_delay: 1

  - platform: mqtt
    name: 'Living_room_remote'
    state_topic: 'home/living_room_remote'
    off_delay: 1

  - platform: mqtt
    name: 'Office Door'
    state_topic: 'home/office_door'
    device_class: door

  - platform: mqtt
    name: 'Office Window'
    state_topic: 'home/office_window'
    device_class: window

  - platform: mqtt
    name: 'My Closet'
    state_topic: 'home/my_closet'
    device_class: door

  - platform: mqtt
    name: "Crystal Closet"
    state_topic: 'home/crystal_closet'
    device_class: door

  - platform: mqtt
    name: "Laundry Room"
    state_topic: 'home/laundry_door'
    device_class: door

  - platform: mqtt
    name: "Storage Room"
    state_topic: 'home/storage_door'
    device_class: door

plant:
  office:
    sensors:
      moisture: sensor.plant_soil_moisture
    min_moisture: 50
    max_moisture: 80

scene:
  platform: hunterdouglas_powerview
  address: 10.0.0.248

sleepiq:
  username: !secret sleepiq_username
  password: !secret sleepiq_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

recorder:
  db_url: !secret mysql_url

rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

mqtt:
  discovery: true
  discovery_prefix: 'homeassistant'
  broker: mosquitto_core
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

weather:
  - platform: darksky
    api_key: !secret dark_sky_api

python_script:

light:
  - platform: group
    name: Office Lights
    entities:
      - light.office_lohas_1
      - light.office_lohas_2
  - platform: group
    name: Laundry Lights
    entities:
      - light.laundry_bulb_1
      - light.laundry_bulb_2
  - platform: group
    name: Kitchen Lights
    entities:
      - light.hue_ambiance_downlight_1
      - light.hue_ambiance_downlight_2
      - light.hue_ambiance_downlight_3
      - light.hue_ambiance_downlight_4

panel_custom:
  - name: tasmota
    sidebar_title: Tasmota Devices
    sidebar_icon: mdi:devices
    url_path: tasmota

circadian_lighting:
  max_colortemp: 6500
  min_colortemp: 2000
  transition: 10

switch:
  - platform: circadian_lighting
    name: office
    lights_ct:
      - light.office_lights

octoprint:
  host: 10.0.0.44
  api_key: 2C2F3856FCDB4D82A49E3F750872CBF7
  bed: true
  number_of_tools: 1

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://10.0.0.44/webcam/?action=snapshot
    mjpeg_url: http://10.0.0.44/webcam/?action=stream
