---
cloud:

config:

history:
  include:
    domains:
      - sensor
      - switch
      - person
      - binary_sensor

logbook:
  exclude:
    domains:
      - sun

mobile_app:

person:

ssdp:

sun:

system_health:

zeroconf:

homeassistant:
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes

ring:
  username: !secret ring_email
  password: !secret ring_password

sensor:
  platform: ring

binary_sensor:
  - platform: ring

  - platform: mqtt
    name: 'Xmas_tree_remote_on'
    state_topic: 'home/remote_1_button_1'
    off_delay: 1

  - platform: mqtt
    name: 'Xmas_tree_remote_off'
    state_topic: 'home/remote_1_button_2'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b1'
    state_topic: 'home/office_remote_b1'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b2'
    state_topic: 'home/office_remote_b2'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b3'
    state_topic: 'home/office_remote_b3'
    off_delay: 1

  - platform: mqtt
    name: 'Office_remote_b4'
    state_topic: 'home/office_remote_b4'
    off_delay: 1

  - platform: mqtt
    name: 'Living_room_remote_on'
    state_topic: 'home/living_room_remote_on'
    off_delay: 1

camera:
  - platform: ring

plant:
  office:
    sensors:
      moisture: sensor.plant_soil_moisture
    min_moisture: 50
    max_moisture: 80

scene:
  platform: hunterdouglas_powerview
  address: 10.0.0.6

sleepiq:
  username: !secret sleepiq_username
  password: !secret sleepiq_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

recorder:
  db_url: !secret mysql_url

rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

mqtt:
  discovery: true
  discovery_prefix: 'homeassistant'
  broker: mosquitto_core
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

device_tracker:
  - platform: xfinity
    host: 10.0.0.1
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
    interval_seconds: 30
    consider_home: 180

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_token
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

weather:
  - platform: darksky
    api_key: b989fe8800c82df65727932a5d1d1118

python_script:

light:
  - platform: group
    name: Office Lights
    entities:
      - light.office_lohas_1
      - light.office_lohas_2

panel_custom:
  - name: tasmota
    sidebar_title: Tasmota Devices
    sidebar_icon: mdi:devices
    url_path: tasmota

vera:
  vera_controller_url: http://10.0.133:3480/

