---
title: Home
views:
  - badges: []
    cards:
      - entity: weather.dark_sky
        name: 'Blue Springs, MO'
        type: weather-forecast
      - entities:
          - entity: binary_sensor.ring_front_door_ding
          - entity: binary_sensor.ring_front_door_motion
        title: Front Door
        type: glance
      - entities:
          - person.crystal_luzynski
          - person.sarah_luzynski
          - person.steve_luzynski
        title: People
        type: entities
        show_header_toggle: false
      - type: picture-entity
        entity: camera.front_door
        camera_view: live
        state_filter:
          - null
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: sensor.basement_temperature
          - entity: sensor.basement_humidity
          - entity: binary_sensor.office_motion_sensor_9
        show_header_toggle: false
        title: Office
        type: entities
      - type: plant-status
        entity: plant.office
        name: Office Plant
      - type: entities
        entities:
          - entity: sensor.circadian_values
          - entity: light.office_lights
        show_header_toggle: false
        title: Overhead Light
#      - type: custom:light-with-profiles
#        title: Office Light
#        entities:
#          - entity: light.office_lights
#            name: 'Overhead Lights'
#            profiles:
#              - name: relax
#                icon: mdi:meditation
#              - name: energize
#                icon: mdi:bike
#              - name: reading
#                icon: mdi:library
      - type: light
        entity: light.wledoffice
        name: Office WLed
      - entity: media_player.office_home_mini
        type: media-control
    path: office
    title: Office
  - badges: []
    cards:
      - entity: media_player.family_room
        type: media-control
      - entity: media_player.xbr_75x850e
        type: media-control
      - entities:
          - sensor.living_room_temperature
          - sensor.living_room_humidity
        show_header_toggle: false
        title: Environment
        type: entities
      - entities:
          - entity: scene.33310
            type: entity-button
            name: Open all
            tap_action:
              action: call-service
              service: scene.turn_on
          - entity: scene.15890
            type: entity-button
            name: Close all
            tap_action:
              action: call-service
              service: scene.turn_on
        type: glance
        title: Shades
      - type: entity-button
        entity: switch.retro_lamp
        name: Retro Lamp
        icon: mdi:lamp
      - type: entity-button
        entity: switch.behind_couch
        name: Ikea Lamps Behind Couch
        icon: mdi:lamp
      - type: entity-button
        entity: switch.xmas_tree
        name: Xmas Tree
        icon: mdi:pine-tree
    path: living-room
    title: Living Room
  - badges: []
    cards:
      - type: "custom:light-entity-row"
        entity: light.sarah_lights
        showColorPicker: true # shows color picker if supported
        showColorSliders: false # shows hue/saturation sliders if supported
        showColorTemp: true
      - entities:
          - sensor.sarah_s_room_temperature
          - sensor.sarah_s_room_humidity
        show_header_toggle: false
        title: Sarah's Room
        type: entities
    path: sarahs-room
    title: Sarah's Room
  - badges: []
    cards:
      - entity: media_player.kitchen
        type: media-control
      - entity: light.kitchen_led
        type: light
    path: kitchen
    title: Kitchen
  - badges: []
    cards:
      - entities:
          - sensor.master_bedroom_temperature
          - sensor.master_bedroom_humidity
        show_header_toggle: false
        title: Master Bedroom
        type: entities
      - entities:
          - binary_sensor.sleepnumber_steve_steve_is_in_bed
          - binary_sensor.sleepnumber_steve_crystal_is_in_bed
        title: Bed
        type: entities
        show_header_toggle: false
      - entity: media_player.master_bedroom
        type: media-control
    path: master-bedroom
    title: Master Bedroom
  - badges: []
    cards:
      - entities:
        - lock.back_door_8
        type: entities
        show_header_toggle: false
        title: Back Door Lock
    title: Basement
    path: basement
  - badges: []
    cards:
      - entities:
        - binary_sensor.utility_room_water_10
        show_header_toggle: false
        type: entities
        title: Water Sensors
    title: Utility Room
    path: utility-room
  - badges: []
    cards:
      - entities:
        - entity: light.splash_light_1
        - type: 'custom:rgb-light-card'
          entity: light.splash_light_1
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - rgb_color:
              - 255
              - 0
              - 0
              brightness: 255
              transition: 1
        - entity: light.splash_light_2
        - type: 'custom:rgb-light-card'
          entity: light.splash_light_2
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - rgb_color:
              - 255
              - 0
              - 0
              brightness: 255
              transition: 1
        title: Front Yard Splash Lights
        type: entities
      - entities:
        - entity: light.front_porch_light
          type: 'custom:rgb-light-card'
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - kelvin: 6000
              brightness: 220
              transition: 1
              icon_color: '#ffffff'
            - kelvin: 2700
              brightness: 220
              transition: 1
              icon_color: '#ffa957'
            - rgb_color:
              - 0
              - 0
              - 255
              brightness: 255
              transition: 1
        title: Front Porch Light
        type: entities

    title: Front Yard
    path: front-yard
  - badges: []
    cards:
      - entities:
          - entity: light.wled_porch
          - entity: sensor.wled_porch_estimated_current
          - entity: sensor.wled_porch_free_memory
        title: Deck LED Strip
        type: entities
        show_header_toggle: false
    title: Back Yard
    path: back-yard
  - badges: []
    cards:
      - entities:
          - sensor.sarah_s_room_temperature
          - sensor.sarah_s_room_humidity
          - sensor.basement_temperature
          - sensor.basement_humidity
          - sensor.master_bedroom_temperature
          - sensor.master_bedroom_humidity
          - sensor.living_room_temperature
          - sensor.living_room_humidity
        type: history-graph
    panel: true
    path: temperature-graphs
    title: Temperature History

# Custom lovelace cards, etc.
resources:
  - url: https://cdn.jsdelivr.net/npm/rgb-light-card
    type: js

  - url: /community_plugin/light-entity-row/light-entity-row.js
    type: js

  - type: module
    url: /local/community/lovelace-light-with-profiles/light-with-profiles.js

# included here so custom light profile card can show active profile
light_profiles:
  relax: '0.5119,0.4147,144'
  concentrate: '0.5119,0.4147,219'
  energize: '0.368,0.3686,203'
  reading: '0.4448,0.4066,240'
