---
title: Home
views:
  - badges: []
    title: Home
    path: default_view
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
        name: 'Blue Springs, MO'
      - type: entities
        title: People
        show_header_toggle: false
        entities:
          - person.crystal_luzynski
          - person.sarah_luzynski
          - person.steve_luzynski

  - badges: []
    title: Office
    path: office
    cards:
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - entity: sensor.basement_temperature
          - entity: sensor.basement_humidity
          - entity: binary_sensor.office_motion_sensor_9
          - entity: binary_sensor.office_door
          - entity: binary_sensor.office_window
      - type: plant-status
        name: Office Plant
        entity: plant.office
      - type: entities
        title: Overhead Light
        show_header_toggle: false
        entities:
          - entity: sensor.circadian_values
          - entity: light.office_lights
          - entity: switch.office_sonoff_mini
            name: "Office Light Switch"
      - type: light
        name: Office WLed
        entity: light.wledoffice
      - type: media-control
        entity: media_player.office_home_mini

  - badges: []
    title: Living Room
    path: living-room
    cards:
      - type: media-control
        entity: media_player.family_room
      - type: media-control
        entity: media_player.xbr_75x850e
      - type: entities
        title: Environment
        show_header_toggle: false
        entities:
          - sensor.living_room_temperature
          - sensor.living_room_humidity
      - type: glance
        title: Shades
        entities:
          - entity: scene.33310
            type: entity-button
            name: Open all
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.33310
          - entity: scene.15890
            type: entity-button
            name: Close all
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.15890
      - type: glance
        title: Lights
        entities:
        - entity: switch.retro_lamp
          icon: mdi:floor-lamp
        - entity: switch.behind_couch
          icon: mdi:floor-lamp-dual

  - badges: []
    title: Sarah's Room
    path: sarahs-room
    cards:
      - type: glance
        entities:
          - entity: sensor.sarah_s_room_temperature
          - entity: sensor.sarah_s_room_humidity

  - badges: []
    title: Kitchen
    path: kitchen
    cards:
      - type: media-control
        entity: media_player.kitchen
      - type: light
        entity: light.kitchen_led

  - badges: []
    title: Master Bedroom
    path: master-bedroom
    cards:
      - type: glance
        title: Environment
        entities:
          - entity: sensor.master_bedroom_temperature
          - entity: sensor.master_bedroom_humidity
      - type: glance
        title: Bed
        entities:
          - entity: binary_sensor.sleepnumber_steve_steve_is_in_bed
          - entity: binary_sensor.sleepnumber_steve_crystal_is_in_bed
      - type: entities
        title: Closets
        show_header_toggle: false
        entities:
          - entity: light.my_closet_bulb
            name: My Closet Bulb
          - binary_sensor.my_closet
          - entity: light.c_closet_bulb
            name: Crystal Closet Bulb
          - binary_sensor.crystal_closet
      - type: media-control
        entity: media_player.master_bedroom

  - badges: []
    title: Basement
    path: basement
    cards:
      - type: glance
        title: Back Door
        entities:
        - entity: lock.back_door_8
      - type: entities
        title: 3d Printer Status
        show_header_toggle: false
        entities:
        - binary_sensor.octoprint_printing
        - binary_sensor.octoprint_printing_error
        - sensor.octoprint_current_state
        - sensor.octoprint_job_percentage
        - sensor.octoprint_time_elapsed
        - sensor.octoprint_time_remaining
        - sensor.octoprint_target_bed_temp
        - sensor.octoprint_actual_bed_temp
        - sensor.octoprint_target_tool0_temp
        - sensor.octoprint_actual_tool0_temp

  - badges: []
    title: Utility Room
    path: utility_room
    cards:
      - type: glance
        title: Water Sensors
        entities:
        - entity: binary_sensor.utility_room_water_10

  - badges: []
    title: Front Yard
    path: front-yard
    cards:
      - type: entities
        title: Splash Lights
        show_header_toggle: false
        entities:
        - entity: light.splash_light_1
        - type: 'custom:rgb-light-card'
          entity: light.splash_light_1
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - rgb_color:
              - 255
              - 0
              - 0
              brightness: 255
              transition: 1
        - entity: light.splash_light_2
        - type: 'custom:rgb-light-card'
          entity: light.splash_light_2
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - rgb_color:
              - 255
              - 0
              - 0
              brightness: 255
              transition: 1

  - badges: []
    title: History Graphs
    path: history-graphs
    panel: true
    cards:
      - type: history-graph
        title: Temperature History
        entities:
          - sensor.sarah_s_room_temperature
          - sensor.sarah_s_room_humidity
          - sensor.basement_temperature
          - sensor.basement_humidity
          - sensor.master_bedroom_temperature
          - sensor.master_bedroom_humidity
          - sensor.living_room_temperature
          - sensor.living_room_humidity

# Custom lovelace cards, etc.
resources:
  - url: https://cdn.jsdelivr.net/npm/rgb-light-card
    type: js

  - url: /community_plugin/light-entity-row/light-entity-row.js
    type: js

  - type: module
    url: /local/community/lovelace-light-with-profiles/light-with-profiles.js