---
title: Home
views:
  - badges: []
    title: Home
    path: default_view
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
        name: 'Blue Springs, MO'
      - type: glance
        title: People
        entities:
          - entity: person.crystal_luzynski
          - entity: person.sarah_luzynski
          - entity: person.steve_luzynski

  - badges: []
    title: Office
    path: office
    cards:
      - type: entities
        title: Office
        show_header_toggle: false
        entities:
          - entity: sensor.basement_temperature
            name: "Office Temperature"
          - entity: sensor.basement_humidity
            name: "Office Humidity"
          - entity: binary_sensor.office_door
          - entity: binary_sensor.office_window
      - type: plant-status
        name: Office Plant
        entity: plant.office
      - type: entities
        title: Overhead Light
        show_header_toggle: false
        state_color: true
        entities:
          - entity: switch.circadian_lighting_office
            name: Circadian Adjustments
          - entity: light.office_lights
          - entity: switch.office_sonoff_mini
            name: "Office Light Switch"
          - entity: switch.office_fan
      - type: light
        name: Office WLed
        entity: light.wledoffice
      - type: media-control
        entity: media_player.office_home_mini

  - badges: []
    title: Living Room
    path: living-room
    cards:
      - type: media-control
        entity: media_player.family_room
      - type: media-control
        entity: media_player.xbr_75x850e
      - type: glance
        title: Environment
        entities:
          - entity: sensor.living_room_temperature
          - entity: sensor.living_room_humidity
      - type: glance
        title: Shades
        entities:
          - entity: scene.33310
            type: entity-button
            name: Open all
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.33310
          - entity: scene.15890
            type: entity-button
            name: Close all
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.15890
      - type: glance
        title: Lights
        entities:
        - entity: switch.retro_lamp
          name: "Retro Lamp"
          icon: mdi:floor-lamp
          tap_action:
            action: toggle
        - entity: group.ikea
          name: "Ikea Lights"
          icon: mdi:floor-lamp-dual
          tap_action:
            action: toggle
        - entity: light.living_room_north_downlight
          name: "North Downlight"
          tap_action:
            action: toggle
        - entity: light.living_room_south_downlight
          name: "South Downlight"
          tap_action:
            action: toggle
        - entity: light.garage_entry_downlight
          name: "Garage Entry Downlight"
          tap_action:
            action: toggle

  - badges: []
    title: Sarah's Room
    path: sarahs-room
    cards:
      - type: glance
        entities:
          - entity: sensor.sarah_s_room_temperature
          - entity: sensor.sarah_s_room_humidity
      - type: glance
        title: Lights
        entities:
          - entity: light.1
          - entity: light.2
          - entity: light.3

  - badges: []
    title: Kitchen
    path: kitchen
    cards:
      - type: media-control
        entity: media_player.kitchen
      - type: glance
        title: Lights
        entities:
          - entity: light.kitchen_led
            name: Color Strip over Cabinets
            tap_action:
              action: toggle
          - entity: light.kitchen_lights
            name: Kitchen Lights
            tap_action:
              action: toggle
      - type: glance
        title: Laundry Room
        entities:
          - entity: light.laundry_lights
            tap_action:
              action: toggle
          - entity: binary_sensor.laundry_room

  - badges: []
    title: Master Bedroom
    path: master-bedroom
    cards:
      - type: glance
        title: Environment
        entities:
          - entity: sensor.master_bedroom_temperature
          - entity: sensor.master_bedroom_humidity
      - type: glance
        title: Bed
        entities:
          - entity: binary_sensor.sleepnumber_steve_steve_is_in_bed
            icon: mdi:bed-king
          - entity: binary_sensor.sleepnumber_steve_crystal_is_in_bed
            icon: mdi:bed-king
      - type: entities
        title: Closets
        show_header_toggle: false
        entities:
          - entity: light.my_closet_bulb
            name: My Closet Bulb
          - binary_sensor.my_closet
          - entity: light.c_closet_bulb
            name: Crystal Closet Bulb
          - binary_sensor.crystal_closet
      - type: media-control
        entity: media_player.master_bedroom

  - badges: []
    title: Basement
    path: basement
    cards:
      - type: gauge
        entity: sensor.basement_motion_temperature
        name: "Basement Temperature"
      - type: glance
        title: Lights
        entities:
        - entity: light.basement_stairs_downlight
          name: Stairs
          tap_action:
            action: toggle
        - entity: switch.storage_sonoff_mini
          name: Storage Room Lights
          icon: mdi:lightbulb
          tap_action:
            action: toggle
        - entity: binary_sensor.storage_room
          name: Storage Room
          icon: mdi:door
      - type: entities
        title: 3d Printer Status
        show_header_toggle: false
        entities:
        - binary_sensor.octoprint_printing
        - binary_sensor.octoprint_printing_error
        - sensor.octoprint_current_state
        - sensor.octoprint_job_percentage
        - sensor.octoprint_time_elapsed
        - sensor.octoprint_time_remaining
        - sensor.octoprint_target_bed_temp
        - sensor.octoprint_actual_bed_temp
        - sensor.octoprint_target_tool0_temp
        - sensor.octoprint_actual_tool0_temp

  - badges: []
    title: Front Yard
    path: front-yard
    cards:
      - type: entities
        title: Splash Lights
        show_header_toggle: false
        entities:
        - entity: light.splash_light_1
        - type: 'custom:rgb-light-card'
          entity: light.splash_light_1
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - rgb_color:
              - 255
              - 0
              - 0
              brightness: 255
              transition: 1
        - entity: light.splash_light_2
        - type: 'custom:rgb-light-card'
          entity: light.splash_light_2
          colors:
            - rgb_color:
              - 0
              - 255
              - 0
              brightness: 255
              transition: 1
            - rgb_color:
              - 255
              - 0
              - 0
              brightness: 255
              transition: 1

  - badges: []
    title: History Graphs
    path: history-graphs
    panel: true
    cards:
      - type: history-graph
        title: Temperature History
        entities:
          - sensor.sarah_s_room_temperature
          - sensor.sarah_s_room_humidity
          - entity: sensor.basement_temperature
            name: "Office Temperature"
          - entity: sensor.basement_humidity
            name: "Office Humidity"
          - sensor.master_bedroom_temperature
          - sensor.master_bedroom_humidity
          - sensor.living_room_temperature
          - sensor.living_room_humidity
          - entity: sensor.basement_motion_temperature
            name: "Basement Temperature"

# Custom Header configuration
custom_header:
  compact_mode: true
  hide_help: true
  hide_unused: true
  hide_config: true

# Custom lovelace cards, etc.
resources:
  - url: https://cdn.jsdelivr.net/npm/rgb-light-card
    type: js

  - url: /community_plugin/light-entity-row/light-entity-row.js
    type: js

  - type: module
    url: /local/community/lovelace-light-with-profiles/light-with-profiles.js

  - url: 'https://fonts.googleapis.com/css?family=Raleway'
    type: css

  - url: /local/popup-background.js
    type: js

  - url: /community_plugin/custom-header/custom-header.js
    type: module
